### ISSUE TITLE
LinkedIn peofile link is not opening 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [Aryainguz/Aryainguz.github.io#1]
Hey, 
In the About section, the LinkedIn profile link is not opening.

**Comment by Aryainguz** [comment]
> 

Hey Bama, I just checked and I found out it’s working, it might not be working on your device because you mightn’t have been logged in to LinkedIn the device you opened up the site, check on device after logging in on linkedin on your device, cheers

**Comment by BamaCharanChhandogi** [comment]
The link you provided in your HTML code is not correct. 
This is the proper link:  **https://www.linkedin.com/in/aryan-b73150254/**

**Comment by Aryainguz** [comment]
> The link you provided in your HTML code is not correct.
> This is the proper link: **https://www.linkedin.com/in/aryan-b73150254/**

Yes I recently changed my LinkedIn username and not the link in code and that’s probably why the link wasn’t working, thanks for the help

**Comment by BamaCharanChhandogi** [comment]
ok, Thanks
